name: Generate Matrix
description: GitHub Action to create a dynamic Silverstripe CI matrix

inputs:
  # Extra jobs must be multi-line string, as there's no support for type: array for inputs
  extra_jobs:
    type: string
    required: false
    default: ''
  # Simple matrix will only run a single job with the lowest supported PHP and mysql versions instead of a full matrix
  simple_matrix:
    type: boolean
    default: false
  endtoend:
    type: boolean
    default: true
  # This option is intended only for community modules
  # Modules on silverstripe account will ignore this value and always run codecov
  phpcoverage:
    type: boolean
    default: false
  # This option is specifically for turning off codecov on modules on the silverstripe account
  # Use this if there are something like segfaults during a codecov run
  phpcoverage_force_off:
    type: boolean
    default: false
  phplinting:
    type: boolean
    default: true
  phpunit:
    type: boolean
    default: true
  js:
    type: boolean
    default: true

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
outputs:
  matrix:
    description: JSON matrix
    value: ${{ steps.php-script.outputs.matrix }}

runs:
  using: composite
  steps:

    - name: Set fetch depth
      id: set-fetch-depth
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      shell: bash
      run: |
        # Default fetch-depth of 1 will only fetch the latest commit
        # This is fine for non-pull-request events where standard major.minor naming conventions
        # are used so we do not need to attempt to get the name of the parent branch
        FETCH_DEPTH=1
        # For pull-requests, set fetch-depth to one more than the number of commits
        # so we can later make a best attempt at getting the name of the parent branch
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          PR_NUMBER=${{ github.event.pull_request.number }}
          # https://docs.github.com/en/rest/pulls/pulls#list-commits-on-a-pull-request
          RESP_CODE=$(curl -w %{http_code} -s -o __pr_commits.json \
            -X GET https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/commits \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ github.token }}" \
          )
          if [ "$RESP_CODE" == 200 ]; then
            FETCH_DEPTH=$(cat __pr_commits.json | jq '. | length + 1')
            rm __pr_commits.json
          else
            echo "Failed to fetch commits for pull-request - HTTP response code was $RESP_CODE"
            exit 1
          fi
        fi
        echo "FETCH_DEPTH is $FETCH_DEPTH"
        echo "::set-output name=fetch-depth::$FETCH_DEPTH"

    - name: Checkout code
      uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2.4.2
      with:
        fetch-depth: ${{ steps.set-fetch-depth.outputs.fetch-depth }}

    - name: Install PHP
      uses: shivammathur/setup-php@3eda58347216592f618bb1dff277810b6698e4ca # v2.19.1
      with:
        php-version: '8.1'
        extensions: yaml

    - name: Create __inputs.yml
      shell: bash
      # Add string inputs to memory instead of using string substituion in shell script
      # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
      env:
        EXTRA_JOBS: ${{ inputs.extra_jobs }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # github.base_ref is the target branch on a pull-request
        # github.ref_name is the name of the branch on push, and the tag on tag
        GITHUB_MY_REF: ${{ github.base_ref || github.ref_name }}
      run: |
        # Escape double quotes '"' => '\"'
        EXTRA_JOBS=${EXTRA_JOBS//\"/\\\"}
        GITHUB_MY_REF=${GITHUB_MY_REF//\"/\\\"}
        rm -f __inputs.yml
        # E.g. push event to branch called myaccount-patch-1
        # Use git history to make a best attempt at getting the parent branch
        PARENT_BRANCH=$(git show-branch -a 2>/dev/null | grep -F '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n 1 | sed -e 's/.*\[\(.*\)\].*/\1/' | sed -e 's/[\^~].*//' || true)
        # Create __inputs.yml
        {
          echo "endtoend: ${{ inputs.endtoend }}"
          echo "js: ${{ inputs.js }}"
          echo "phpcoverage: ${{ inputs.phpcoverage }}"
          echo "phpcoverage_force_off: ${{ inputs.phpcoverage_force_off }}"
          echo "phplinting: ${{ inputs.phplinting }}"
          echo "phpunit: ${{ inputs.phpunit }}"
          echo "simple_matrix: ${{ inputs.simple_matrix }}"
          echo "github_repository: '$GITHUB_REPOSITORY'"
          echo "github_my_ref: '$GITHUB_MY_REF'"
          echo "parent_branch: '$PARENT_BRANCH'"
          if [ -n "$EXTRA_JOBS" ]; then
            echo "extra_jobs:"
            echo "$EXTRA_JOBS"
          fi
        } > __inputs.yml
        echo "Contents of __inputs.yml"
        cat __inputs.yml

    - name: Run php script
      id: php-script
      shell: bash
      run: |
        MATRIX_JSON=$(php ${{ github.action_path }}/action.php)
        echo "MATRIX_JSON: $MATRIX_JSON"
        echo "::set-output name=matrix::${MATRIX_JSON}"
